apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset-darshan
  namespace: webapp-namespace-darshan
  labels:
    app: employees  
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: employees  
  template:
    metadata:
      labels:
        app: employees  
    spec:
      containers:
      - name: webapp
        image: 463946470401.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:Darshan
        env:
        - name: DBHOST
          value: "dhmodi1db.mysql-namespace-darshan.svc.cluster.local"  
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "password"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-registry-secret  
